#!/usr/bin/env ruby

# kept simple so maybe it can be converted back into shellscript


# splits two arrays into their similarities and differences.
# given [a, b, c] and [a, b, d, e] returns [[a, b], [c], [d, e]]
def common_prefix a, b
  smaller_size = [a.length, b.length].min
  smaller_size.times do |i|
    if a[i] != b[i]
      return a.take(i), a[i..-1], b[i..-1]
    end
  end
  return a, a[smaller_size..-1], b[smaller_size..-1]
end


oldpath = []
STDIN.each_line do |line|
  page,fullpath = line.split(' ', 2)
  path = fullpath.split('/')

  prefix,outgoing,incoming = common_prefix(oldpath, path)
  outgoing.reverse.each { |o| puts "pop #{o}" }
  incoming.each { |o| puts "push #{page} #{o}" }
  oldpath = path
end
oldpath.reverse.each { |o| puts "pop #{o}" }
