#!/bin/bash
#
# pdfdir-copy
# Scott Bronson
# 16 May 2009
#
# Uses ghostscript to re-encode an entire directory of PDF files.
# This is the best way to remove encryption and recompress but it
# does take quite a lot of CPU time.
#
# We don't bomb out on empty files.  We probably should.
# We do bomb out on random files.
#   TODO: watch the output for 0-page files.  Print them.
#
# usage: pdfdir-copy destination-dir
#   copies all the pdfs in the current directory and all its subdirs
#   to the specified destination-dir

output="$1"
mkdir -p "$output" || exit

find . -name "*.pdf" | while read i; do
	echo "$i"
	echo "$i" >> /tmp/errout
	mkdir -p "$output/$(dirname "$i")"
	gs -sDEVICE=pdfwrite -sOUTPUTFILE="$output/$i" -dBATCH -dNOPAUSE "$i" 2>>/tmp/errout || echo "$i" >> /tmp/badfiles
done

